changed method AclRuleL3::validateAddAction() and AclRuleL3::getRedir…
madhanmellanox/sonic-swss pull request #1
Opened 2020-03-24 02:46 UTC by madhanmellanox

…ectObjectId() to handle all ACL redirect cases

**What I did**
I made changes to methods AclRuleL3()::validateAddAction() and AclRuleL3::getRedirectObject() in order to accomodate all type of ACL redirect commands.

**Why I did it**
Because, the current code had some assumptions on how the ACL redirect request should be parsed in the ACL orchagent. I removed the assumption.

**How I verified it**
I verified it by testing different kinds of ACL redirect commands on my switch.

**Details if related**

2020-03-24 14:34 UTC, stepanblyschak requested changes

2020-03-24 14:34 UTC, stepanblyschak commented on orchagent/aclorch.cpp
> +            if (attr_value[colon_pos] != ':')
This line has UB: if attr_value.length() == colon_pos (e.g.: attr_value == PACKET_ACTION_REDIRECT) it reads behind the allocated string heap (or stack depending on SSO in std library and string size).
Note: c_str() will guaranty to insert '\0' at the end and the above code will become valid.

2020-03-25 02:19 UTC, madhanmellanox commented on orchagent/aclorch.cpp
> +            if (attr_value[colon_pos] != ':')
I handled this case in the next commit. Thanks.

2020-11-30 19:31 UTC, madhanmellanox commented
This is an internal PR and Azure PR corresponding to this one got merged, so closing this one.

2020-11-30 19:31 UTC, closed without merging